export const UserActions = {
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILED: 'LOGIN_FAILED',
	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILED: 'LOGOUT_FAILED',
	LOGIN_ERROR: 'LOGIN_ERROR',

	SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILED: 'SIGN_UP_FAILED',
	SIGN_UP_ERROR: 'SIGN_UP_ERROR',

	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

	OPEN_DELETE_MODAL: 'OPEN_DELETE_MODAL',
	CLOSE_DELETE_MODAL: 'CLOSE_DELETE_MODAL',

	OPEN_REPLY_MAIN_COMMENT_BOX:"OPEN_REPLY_MAIN_COMMENT_BOX",
	CLOSE_REPLY_MAIN_COMMENT_BOX:"CLOSE_REPLY_MAIN_COMMENT_BOX",

	OPEN_REPLY_SIDE_COMMENT_BOX:"OPEN_REPLY_SIDE_COMMENT_BOX",
	CLOSE_REPLY_SIDE_COMMENT_BOX:"CLOSE_REPLY_SIDE_COMMENT_BOX"	,

	FETCH_FEED_POSTS: "FETCH_FEED_POSTS",
	FETCH_INDIVIDUAL_POST: "FETCH_INDIVIDUAL_POST",
	ON_COMMENT: 'ON_COMMENT',
	ON_LIKE: 'ON_LIKE',

	ON_FOLLOW: 'ON_FOLLOW',
	ON_UNFOLLOW: 'ON_UNFOLLOW',

	SEARCH_ALL_POSTS: 'SEARCH_ALL_POSTS',
	SEARCH_USERS: 'SEARCH_USERS',
	SEARCH_MY_POSTS: 'SEARCH_MY_POSTS'


}
